server {
  listen 80;
  server_name localhost;

  root /usr/share/nginx/html;
  index index.html;

  location / {
    try_files $uri $uri/ /index.html;
  }

  location /api/ {
    # FIX: Use the full, correct Kubernetes Service Name
    proxy_pass http://three-tier-app-my-3-tier-app-backend:5000/api/;
    
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }

  # static cache headers for assets
  location ~* \\.(?:js|css|png|jpg|jpeg|gif|ico|svg)$ {
    expires 30d;
    add_header Cache-Control "public, no-transform";
  }
}
